version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      DB_HOST: database
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: password
  spboot-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=srgn
      - RABBITMQ_DEFAULT_PASS=srgn